version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nexthire-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 120303
      POSTGRES_DB: nexthire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: nexthire-backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:120303@db:5432/nexthire
      - SECRET_KEY=yoursecretkeyhere
      - ALGORITHM=HS256
      - USE_OAUTH=false
      - BACKEND_API_URL=http://localhost:8001
      - GOOGLE_DRIVE_FOLDER_ID=1pyXLZo631ifuqmDW646cPDLDRA2kq-az
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    container_name: nexthire-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

volumes:
  postgres_data:
